baseURL: "https://keerthi-sreenivas.github.io"
languageCode: "en-us"
title: "Keerthi"
theme: master

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD
canonifyURLs:  true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    - identifier: dropdown
      title: Example dropdown menu
      name: Dropdown
      weight: 2
    - identifier: dropdown1
      title: example dropdown 1
      name: example 1
      url: /#
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: example dropdown 2
      name: example 2
      url: /#
      parent: dropdown
      weight: 2

params:
  #title: "Hugo Profile"
  #description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    #defaultTheme: "dark" #"light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #     textColor: "black"
  #     secondaryTextColor: 
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Keerthi"
    subtitle: "I Discover stories with Data"
    content: "A passionate Data Science Graduate student. I love using data to build stories, enhance products and markets. I'm also a food Vlogger and a Photographer!"
    image: "images/me1.jpg"
    button:
      background - color: 
      enable: true
      name: "Resume"
      url: "https://docs.google.com/document/d/1A2Imqn3RDp45EwyV3Pq0SLKz54J5MPOwxfrTdLtym-4/edit?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Keerthi-Sreenivas
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/keerthi-sreenivas-90b78a185/
        - icon: fab fa-instagram
          url: https://www.instagram.com/accounts/login/?next=/keerthi__sreenivas/
      #customIcons:
        #- icon: /fav.png
        #  url: "https://example.com"

  # About
  about:
    enable: true
    title: "I'm Open to work from December 2022"
    image: "/images/me21.jpg"
    content: |-
     -  I'm a Masters in Data Science student with 3+years of academic experience in Python, R, Machine Learning and Big Data. 
     -  I have a strong interest in the the intersection of Technology and Business.
     -  I am currently working as Data Science R Intern at Allogene Therapeutics https://allogene.com. 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "R"
        - "SQL"
        - "PySpark"
        - "ML libraries in Python"
        - "MLOps"
        - "AWS"

  # Experience
  experience:
    enable: true
    items:
      - job: "Data Science R Intern"
        company: "Allogene Therapeutics"
        companyUrl: "https://allogene.com"
        date: "May 2022 - Aug 2022"
        #featuredLink:
        #  enable: true
        # name: "View the project"
         # url: "https://example.com"
        content:
          Working to Develop a Data Issue tracker dashboard that displays the missing values, anomalies and other pre-processing problems in data.
           - Developing a Data Issue Tracking Dashboard to improve productivity in communication between Statistical Programming and Data Management Team
           - Reporting to Director of Statistical Analysis and Data Analytics and R Programmer"

      - job: "Technical Instructor Intern"
        company: "KITOLIT"
        companyUrl: "https://www.kitolit.com"
        date: "Jul 2020 - Nov 2020"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://www.kitolit.com"
        content: |
          Generated a revenue of $6,400 for the startup by offering one-on-one sessions during late/early hours from India for students in the USA, designing course structure and content.

          - Lead Technical Instructor
          - Designed the curriculum and Produced Content for an experiential learning course "Java for Middle School Kids".
          - Took One-on-One classes for Students in the USA during Late/Early hours.


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Masters in Data Science (Business Concentration)"
        school:
          name: "University of Rochester, New York"
          url: "https://www.rochester.edu"
        date: "2021 - 2022"
        GPA: "3.7 out of 4.0"
        content: |-
            - Course Work: Data Science at scale, Machine Learning, Applied Statistical Methods, Data Mining, Technical Entrepreneurship, Time Series analysis and forecasting.
            - Worked as a Teaching Assistant for Big Data at the Simon Business School, University of Rochester
            - Worked as a Research assistant to pre-process Bio-Medical Image data for training a U-Net Deep Learning Algorithm in the Machine Learning team at the Vaccine Biology and Dermatology labs in University Medical Center
            - Attending Grace Hopper 2022 Conference with University Scholarship

            Extracurricular Activities
             - Won first place in the Creative Collision Chanllenge 2022 Pitching competition 
             - Conducted and guided a Zumba workshop under Rochester Indian Association
             - Active member of UR Photography club
      - title: "Bachelor of Technology in Computer Science and Engineering"
        school:
          name: "Indian Institute of Information Technology, Kottayam"
          url: "http://www.iiitkottayam.ac.in/#!/home"
        date: "2017 - 2021"
        GPA: "8.96 out of 10"
        content: |- 
          - Main Author for the research presentation “IoT based Smart Medicine Reminder Kit” at ACM/CSI/IEEE-CS Research and Industry Symposium at IIIT Kottayam.
          - Co-Founded Proxima an Image processing based Start-up for Smart Badminton and Yoga instruction with Feedback using Deeplearning.
          - Data Science Courses: Artificial Intelligence, Data Warehousing and  Data Mining, Big Data Analytics, Predictive Analytics, Database Management, 
          - Computer Science Courses: Cloud Computing, Cryptography and Network Security, Computer Programming, Data Structures, Computer Networks, Computer Organization, Compiler Design, Block Chain Technology, IoT (Internet of Things), Operating Systems, Soft Computing, Distributed and Parallel Computing, High Performance Computing, Theory of Computation, Object Oriented Analysis and Design,
          - Software Management Courses: Software Engineering and Project Management, Software Design Patterns
          - Other Courses: Personality Development, Communication Skills, Economics, Human Resource Management, Financial Management and Accounting, Operation and Supply Chain Management
          
          

          Extracurricular Activities
            - Won 2nd place in Smart India Hackathon 2020 for developing a Smart Yoga Instructor with feedback using Deep Learning
            - Was the Elected Cultural Club Secretary from 2019-2021
            - Won several Photography competitions during all 4 years.

  #featuredLink:
  #enable: true
  #name: "My academic record"
  #url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      - title: Smart India Hackathon 2020
        content: Won 2nd place in Smart India Hackathon 2020 for developing a Smart Yoga Instructor with feedback using Deep Learning
        url: "https://www.sih.gov.in"
      - title: Women Entrepreneur Week Candidate 2020
        content: Was selected to meet a Senior Director from Jio Industries for a discussion about the Smart Yoga Instructor app.
      - title: Elected Cultural Secretary 2019 - 2021
        content: Conducted 15+ events with a footprint of more than 300+ students. Managed a team of 20 students for fundraising and event organization. Conducted events virtually during COVID for effective engagement among new students.
        url: "https://www.iiitkottayam.ac.in/#!/culturalClub"
      - title: Author of “IoT based Smart Medicine Reminder Kit” at ACM/CSI/IEEE-CS Research and Industry Symposium at IIIT Kottayam 
        content: I worked on this project for 1.5 years and was selected to present at the conference

  # projects
  projects:
    enable: true
    items:
      - title: Colorizer - Deep Learning
        content: A Deep learning based application that converts a Black and White (Grayscale) Image/Video into a Colour video without human guidance.
        image: /images/projects/Colorization3.png
        featured:
          name: Click here to know more!
          link: https://docs.google.com/presentation/d/193X-n0sXoFbMR9dD7rxJxwM8n_GpOwNQ/edit?usp=sharing&ouid=116008293600462184270&rtpof=true&sd=true
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          #- icon: fa fa-envelope
          #  url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/Keerthi-Sreenivas/Deep-Learning/blob/main/Gray%20Scale%20Image%20Colorization%20using%20Auto%20Encoders%20(Fruits%20Data%20Set).ipynb
          # - icon: fab fa-twitter
          #  url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Elon Musk Dogecoin Tweet Analysis - NLP
        content: Analyzed the sentiments around Elon's tweets about Dogecoin and impact of his tweets on the price of Doge coin.
        image: /images/projects/doge4.jpeg
        featured:
          name: Click here to know more!
          link: https://github.com/Keerthi-Sreenivas/Elon_Musk-Doge-Tweet_Analysis
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/Keerthi-Sreenivas/Elon_Musk-Doge-Tweet_Analysis

      - title: Marketing Insights - Statistics
        content: Digging through data and finding significant insights to advertise better products to customers of different backgrounds.
        image: /images/projects/advert1.jpeg
        featured:
          name: Click here to know more!
          link: https://github.com/Keerthi-Sreenivas/statistics/blob/main/Project.pdf
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/Keerthi-Sreenivas/statistics/blob/main/Project.pdf

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: keerthikonjety9@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/Keerthi-Sreenivas
      linkedin: https://www.linkedin.com/in/keerthi-sreenivas-90b78a185/
    # twitter: https://twitter.com
      instagram: https://www.instagram.com/keerthi__sreenivas/
    # facebook: https://facebook.com
